### ISSUE TITLE
FreeBSD got error : AttributeError: 'NoneType' object has no attribute 'startswith'            

### ISSUE THREAD

**Issue by bao3** [blueset/ehForwarderBot#153] opened 2019-01-28 11:19 UTC
I installed all the depends , and configured the .yaml ,the I run eFB,but got the following error

```
    from moviepy.video.VideoClip import VideoClip                                                       
  File "/usr/local/lib/python3.6/site-packages/moviepy/video/VideoClip.py", line 18, in <module>        
    from ..config import get_setting                                                                    
  File "/usr/local/lib/python3.6/site-packages/moviepy/config.py", line 35, in <module>                 
    FFMPEG_BINARY = get_exe()                                                                           
  File "/usr/local/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 104, in get_exe         
    if plat.startswith("win"):                                                                          
AttributeError: 'NoneType' object has no attribute 'startswith'                                         
Error in atexit._run_exitfuncs:                                                                         
Traceback (most recent call last):                                                                      
  File "/usr/local/lib/python3.6/site-packages/ehforwarderbot/__main__.py", line 48, in stop_gracefully 
    if isinstance(coordinator.master, EFBChannel):                                                      
AttributeError: module 'ehforwarderbot.coordinator' has no attribute 'master'   
```

Why I got “  if plat.startswith("win"):  ”  , but I am on freebsd os

**Comment by blueset** [comment] 2019-01-28 17:30
Duplicate of [zulko/moviepy#756](https://github.com/Zulko/moviepy/issues/756).

**Closed by blueset** 2019-01-28 17:30 UTC
Labels: duplicate
