### ISSUE TITLE
 File "main.py", line 85, in init     slaves[obj.channel_id] = obj(q, mutex)

### ISSUE THREAD

**Issue by leoxu1007** [blueset/ehForwarderBot#104] opened 2017-12-18 13:41 UTC
18-12-2017:13:38:11,52 CRITICAL [eh_wechat_slave.py:145]
     Tap "Confirm" to continue.
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    init()
  File "main.py", line 85, in init
    slaves[obj.channel_id] = obj(q, mutex)
  File "/root/ehForwarderBot/plugins/eh_wechat_slave.py", line 133, in __init__
    qrCallback=self.console_qr_code)
  File "/usr/local/lib/python3.5/dist-packages/itchat/components/register.py", line 32, in auto_login
    loginCallback=loginCallback, exitCallback=exitCallback)
  File "/usr/local/lib/python3.5/dist-packages/itchat/components/login.py", line 53, in login
    status = self.check_login()
  File "/usr/local/lib/python3.5/dist-packages/itchat/components/login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "/usr/local/lib/python3.5/dist-packages/itchat/components/login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by blueset** [comment] 2017-12-19 01:06
Please check if you can access Web WeChat with your browser. Possible dupe of #74.

**Comment by leoxu1007** [comment] 2017-12-19 01:46
oh no!! I cant login via web browser.
![0029-12-19 9 44 31](https://user-images.githubusercontent.com/22413258/34136507-2857944a-e4a1-11e7-801b-990408aaa736.png)
it says that an unexpected login detected. for the safety of my account, log in via web browser is banned now.

**Closed** 2017-12-20 00:57 UTC
Labels: EWS, question
